### ISSUE TITLE
jackal's ancillary controllers

### ISSUE THREAD

**Issue by prajwalthakur** [eliatrevisan/biased-mppi#1]
Hi , 
I haven't found the implementation of ancillary controller for jackal robot  .
I looked in this repository and in the following one as well 
https://github.com/tud-airlab/mppi_torch
Has it been not implemented yet ?
Thanks

**Comment by eliatrevisan** [comment]
Hi Prajwal,
The jackal robot is controlled in velocity, and the only ancillary controller in the example is the zero velocity reference.

In the [config file of the jackal example](https://github.com/eliatrevisan/biased-mppi/blob/main/examples/jackal/config.yaml), you can see that sample_null_action=true.
That makes the [mppi_torch](https://github.com/tud-airlab/mppi_torch) sample a zero-input sequence, which is a breaking maneuver since the jackal is velocity-controlled.

You can find examples with different ancillary controllers for the [point robot](https://github.com/eliatrevisan/biased-mppi/blob/main/examples/point_robot/priors.py).

I hope that clarifies!
